language: php
php:
    - '5.5'
    - '5.6'
    - '7.0'
matrix:
    fast_finish: true
    allow_failures:
        - php: '7.0'

before_script:
    - composer self-update
    - composer install --prefer-source --dev

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always
